origin: [37.41024770516164, -6.036976391450395, 100]
building_tall_0: {type: building_tall, pose: {xyz: [-35.1, 34, 0], rpy: [0, 0, 3.141592653589793]}}
building_tall_1: {type: building_tall, pose: {xyz: [-34.7, -50.1, 0], rpy: [0, 0, 0]}}
building_short_2: {type: building_short, pose: {xyz: [-85.4, -9.6, 0], rpy: [0, 0, 1.5707963267948966]}}
crane_3: {type: crane, pose: {xyz: [-34, -6.4, 0], rpy: [0, 0, 5.061454830783555]}}
towerlight_4: {type: towerlight, pose: {xyz: [15.2, 48.9, 0], rpy: [0, 0, 0]}}
towerlight_5: {type: towerlight, pose: {xyz: [51, 22.4, 0], rpy: [0, 0, 0]}}
towerlight_6: {type: towerlight, pose: {xyz: [38.3, -25, 0], rpy: [0, 0, 0]}}
towerlight_7: {type: towerlight, pose: {xyz: [5.3, -55.4, 0], rpy: [0, 0, 0]}}
towerlight_8: {type: towerlight, pose: {xyz: [-35.9, -94.3, 0], rpy: [0, 0, 0]}}
towerlight_9: {type: towerlight, pose: {xyz: [-87.8, -85.4, 0], rpy: [0, 0, 0]}}
towerlight_10: {type: towerlight, pose: {xyz: [-119.5, -53.1, 0], rpy: [0, 0, 0]}}
towerlight_11: {type: towerlight, pose: {xyz: [-109.2, -6.7, 0], rpy: [0, 0, 0]}}
towerlight_12: {type: towerlight, pose: {xyz: [-94.2, 39.7, 0], rpy: [0, 0, 0]}}
towerlight_13: {type: towerlight, pose: {xyz: [-42.8, 56.1, 0], rpy: [0, 0, 0]}}
base_14: {type: base, pose: {xyz: [0.2, -7.1, 0], rpy: [0, 0, 0]}}
base_15: {type: base, pose: {xyz: [0.3, -14.1, 0], rpy: [0, 0, 0]}}
base_16: {type: base, pose: {xyz: [0, 0, 0], rpy: [0, 0, 0]}}
px4_1: {type: drone, ns: uav_1, id: 0, pose: {xyz: [0.2, -7.1, 0], rpy: [0, 0, 0]}}
px4_2: {type: drone, ns: uav_2, id: 1, pose: {xyz: [0.3, -14.1, 0], rpy: [0, 0, 0]}}
